[docs] new sections and more
effxhq/rammahgon pull request #10
Opened 2021-02-23 21:21 UTC by joeyparsons

This includes the following:
- New introduction and feature areas under Getting Started
- Overviews in each major section

2021-02-23 23:18 UTC, euriostigue requested changes

2021-02-23 23:18 UTC, euriostigue commented on docs/first-service.md
> +### effx-yaml definition
This entire section is redundant with the "Resource Types" section.

I personally found this harder to read than the dynamic attribute component.

2021-02-23 23:18 UTC, euriostigue commented on docs/first-team.mdx
> +## Adding your first team
This is another redundant section. I think it's better to re-use the Resource Types UI than restate it here.

2021-02-23 23:18 UTC, euriostigue commented on docs/introduction.md
> +Learn more about effx-cli.
Does this need a link?

2021-02-23 23:18 UTC, euriostigue commented on docs/introduction.md
> +Learn more about our Automations.
Does this need a link?

2021-02-23 23:18 UTC, euriostigue commented on docs/first-migration.mdx
> +![Query by value](/img/migration-go.png)
The spacing here was condensed when I viewed this locally. I think adding some `<br>` will help.

2021-02-23 23:18 UTC, euriostigue commented on docs/introduction.md
> +Our API provides flexibility for users that already have service metadata defined in other formats.  Learn more about our API in the API Overview.
Is there supposed to be a link here?

2021-02-24 00:06 UTC, joeyparsons commented on docs/api-overview.mdx
> +title: API Overview
agreed!

2021-02-24 00:13 UTC, euriostigue approved these changes
Looks good to me!

2021-02-24 00:14 UTC, merged